language: java

before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in gradle.properties.enc -out gradle.properties -d
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in signing.gpg.enc -out signing.gpg -d

jobs:
  include:
    - stage: "Build and Publishing"
      name: "Build"
      script:
        - set -e
        - ./gradlew build
    - name: "Publish to Maven Central"
      if: branch = master AND type = push
      script:
        - set -e
        - ./gradlew publishMavenPublicationToMavenRepository --stacktrace
