language: java
jobs:
  include:
    - stage: Build and Publishing
      name: Build
      script:
        - set -e
        - "./gradlew build jacocoTestReport jacocoTestCoverageVerification"
        - "./gradlew reportCoveralls -Djdk.tls.client.protocols=\"TLSv1,TLSv1.1,TLSv1.2\""
    - name: Publish to Maven Central
      if: branch = master AND type = push
      script:
        - set -e
        - "./gradlew publishMavenPublicationToMavenRepository"
    - name: Publish to Bintray
      if: branch = master AND type = push
      script:
        - set -e
        - "./gradlew bintrayUpload"
before_install:
  - openssl aes-256-cbc -K $encrypted_17192d17e098_key -iv $encrypted_17192d17e098_iv -in encrypted.tar.enc -out encrypted.tar -d
  - tar xvf encrypted.tar
