language: java
jobs:
  include:
    - stage: Build and Publishing
      name: Build
      script:
        - set -e
        - "./gradlew build"
    - name: Publish to Maven Central
      if: branch = master AND type = push
      script:
        - set -e
        - "./gradlew publishMavenPublicationToMavenRepository --stacktrace"

before_install:
  - openssl aes-256-cbc -K $encrypted_91af85ef319a_key -iv $encrypted_91af85ef319a_iv -in encrypted.tar.enc -out encrypted.tar -d
  - tar xvf encrypted.tar
