name: Build and publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Build
        run: ./gradlew build
      - name: Publish to Maven central
        env:
          ORG_GRADLE_PROJECT_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_GPG_KEY_PASSPRHASE: ${{ secrets.GPG_KEY_PASSPRHASE }}
          ORG_GRADLE_PROJECT_OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        if: github.ref == 'refs/heads/master'
        run: ./gradlew publish
